USE customer_behavior;

select * from customer limit 20;

SHOW COLUMNS FROM customer;

-- 1. What is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

-- 2. Which customers used a discount but they still spent more than average amount.
SELECT customer_id,
       purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );

-- 3. which are the top 5 products which highest average review rating
SELECT item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5;

-- 4. compare the average purchase amount between standard and express shipping ( try with other types as well.
select shipping_type, 
round(avg(purchase_amount)) from customer
where shipping_type in ('Standard', 'Express', 'Free Shipping', 'Next Day Air', '2-Day Shipping')
group by shipping_type;

-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, 
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status 
order by total_revenue, avg_spend desc;

-- 6. which 5 products have the highest percentage of purchases with discounts applied.
select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) /count(*)*100,2) as discount_rate
from customer
group by item_purchased 
order by discount_rate desc limit 5;

-- 7. Segment customers into new, returning and loyal based on their total number of previous purchases 
-- and show the count of each segment
with customer_type as ( -- Common Table Expression CTE
select customer_id , previous_purchases,
case 
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from customer
)
select customer_segment , count(*) as "Number of customers"
from customer_type
group by customer_segment;

-- 8.what are the top 3 most purchased within each category?
with item_counts as(
select category, item_purchased,
count(customer_id) as total_orders, 
row_number() over(partition by category order by count(customer_id) desc) as item_rank 
-- why used row number here: ROW_NUMBER() is used when you want exactly N rows per group.
-- DENSE_RANK() is used when you want all ties.
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- 9. are customers who are repeat buyers(more than 5 purchases) are also likely to subscribe?
select subscription_status, 
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;



SELECT @@hostname;

select user();


